- bin/pg_repack.c
- regress/expected/repack.out
This helps avoid possible problems with later strong table locks.
> Gather index info at the same time as table info, rather than later.

- bin/pg_repack.c
Previously, pg_repack shows "ERROR: ERROR: relation foo does not exist" when specify non-existing table. 
Though the first ERROR is from pg_repack and the second ERROR is from PostgreSQL server, some users might think that pg_repack shows error level twice wrongly. So, this patch adds message explain it.
> Improve error message when repack against non-existing table.

- regress/expected/repack_1.out
The 'repack' regression test fails on PostgreSQL 8.4 because the index name
assigned implicitely is different from 9.0 and after.
```
$ cat regress/regression.diffs
*** /home/postgres/pg_repack/pg_repack/regress/expected/repack.out      2015-01-14 15:17:51.569064746 +0900
--- /home/postgres/pg_repack/pg_repack/regress/results/repack.out       2015-01-14 15:44:21.401063661 +0900
***************
*** 325,331 ****
-- => OK
\! pg_repack --dbname=contrib_regression --table=tbl_pk_uk --only-indexes
INFO: repacking indexes of "tbl_pk_uk"
! INFO: repacking index "public"."tbl_pk_uk_col2_col1_key"
INFO: repacking index "public"."tbl_pk_uk_pkey"
-- => OK
\! pg_repack --dbname=contrib_regression --table=tbl_nn_puk
--- 325,331 ----
-- => OK
\! pg_repack --dbname=contrib_regression --table=tbl_pk_uk …
```
> Add a expected out file to run the repack regression test successfully.

- bin/pg_repack.c
If there are two concurrent pg_repack commands are run on the same
table, the one starting later fails with error message:
Another pg_repack command may be running on the table. Please try again.
The document says this is shown as ERROR, but actualy is WARNING.
> Change log level as noted in documentation.

- bin/pg_repack.c
- bin/pgut/pgut.c
- lib/pg_repack.sql.in
- lib/repack.c
This patch contains repack_cleanup_callback() which calls to repack_drop() for cleaning temporary objects. repack_cleanup_callback() will be pushed on stack using pgut_atexit_push() at beginning so that it will pop on abort or exit of program. 
This patch includes one global counter ("temp_obj_num") which counts number of temporary objects created by pg_repack. Correct order of deletion of temporary object as per count avoids unintentional error messages.
> Patch for self cleaning process in pg_repack on error.

- lib/repack.c
By commit 7b1c2a0f2066672b24f6257ec9b8d78a1754f494 in PostgreSQL,
builtins.h is splitted to a new header file ruleutils.h.
The usage of pg_get_indexdef_string in lib/repack.c is affected.
> Include a new header file to build with PostgreSQL 9.5

- lib/repack.c
Per documentation, a negative value for count should result in using DEFAULT_PEEK_COUNT.
> repack_apply(): Use default if count is negative

- bin/pgut/pgut-fe.c
Previously, it is 1 but the reason is not clear.
It seems to be a historical one because pg_reorg has the same exit codes.
> Change exit code for --help and --version.

- lib/repack.c
Concurrent activity on the target table can cause deadlocks when
repack_drop() is doing its job, ie, dropping the temporary objects
created. It is highly likely to occur when pg_repack is interrupted
midway through its processing.
This fixes deadlock reported in issue #55 .
> Make repack_drop() processing robust against deadlocks.

- lib/repack.c
Due to upstream changes (see commit 65c5fcd3 in HEAD) to the index AM API definitions.
> Need to #include pg_am.h directly now to use BTREE_AM_OID.

- lib/repack.c
- regress/expected/repack.out
Upstream changes (see commit c7e27bec in HEAD) now cause reloption values to be emitted with surrounding quotes. That breaks, for example, the outputs of \d commands in one of the tests.
> Fix regression test output

- bin/pg_repack.c
Currently, if pg_repack is running for a table, and if a transaction starts right before the repack_drop section (#6) which updates the table, and does not commit, then pg_repack will hang, waiting for the transaction updating the table to commit. 
This hang can be reproduced by:
1. Run pg_repack in gdb for a table, and set a breakpoint at the elog() call in section 6 (drop) for repack_one_table().
2. When gdb stops at the break point, in a psql session, start a transaction and update the table.
3. In gdb, continue. This should hang (until the transaction in step 2 commits).
This change will call lock_exclusive() to grab an exclusive lock and kill other sessions before calling repack.repack_drop() in repack_one_table(). This will cause step 3 to cancel conflicting backends, and then …
> grab exclusive lock before dropping table

- bin/pg_repack.c
Our customers were faced following issue: pg_repack waits for concurrent vacuum to be complete before swapping tables. Vacuum could be slow on very large tables. Therefore it appears to be real problem.
Since VACUUMs are always outside transaction block, there is no risk that their sessions could see old data. This is why we propose to exclude vacuums (both autovacuums and manual vacuums) from list of vxids to wait.
> Don't wait for concurrent vacuums

- doc/pg_repack.rst
- doc/pg_repack_jp.rst
Since 9.5 is not listed yet in pg_repack_jp.rst added 9.5 as well.
Regression test with Postgres 9.6 passed successfully.
> Add 9.6 to list as a supported Postgres version.

- lib/repack.c
Because commit 23a27b039d94ba359286694831eafe03cd970eef has extended the
type of SPI_processed from uint32 to uint64, pg_repack emit warning when
compiling with PostgreSQL 9.6 or later. To fix that, we cast it to uint64
and change format identifier from %d to %lu.
This change deals with issue #109 .
> Change format identifier of SPI_processed to uint64.

- regress/expected/tablespace_2.out
The recent stable update changed output for calls to
repack.repack_indexdef with the third arg being NULL.
Output gets an additional "TABLESPACE pg_default". So add
another variant of expected output to cover 9.6.2, 9.5.6,
9.4.11 and 9.3.16.
Stable update at https://www.postgresql.org/about/news/1733/
Signed-off-by: Christian Ehrhardt <christian.ehrhardt@canonical.com>
> Fix 'tablespace' regression test for latest postgres minor releases

- bin/pg_repack.c
- doc/pg_repack.rst
- doc/pg_repack_jp.rst
- lib/pg_repack.sql.in
- lib/repack.c
- regress/expected/repack.out
- regress/sql/repack.sql
During repacking table, if a transaction executes INSERT CONFLICT
ON UPDATE/DO NOTHING, because we define BEFORE trigger on target
table, the contents of operation log table becomes inconsistent
easliy. As a result, pg_reapck fails with a high probability.
To resolve this issue, this changes the trigger type from BEFORE
to AFTER. We define AFTER trigger that is the first of the AFTER
trigger to fire on the table.
This fixes issue #106.
> Change trigger type to AFTER trigger.

- bin/pg_repack.c
- doc/pg_repack.rst
- doc/pg_repack_jp.rst
- regress/expected/repack.out
- regress/sql/repack.sql
pg_repack needs to take an exclusive lock at the end of the
reorganization. If the lock cannot be taken after duration
--wait-timeout option specified and this option is true,
pg_repack gives up to repack a target table instead of
cancelling conflicting backend. False by default.
> Introduce --dont-kill-backend option.

- bin/pg_repack.c
- doc/pg_repack.rst
- regress/expected/repack.out
- regress/sql/repack.sql
The current client checks for superuser before attempting to
execute pg_repack commands. In Amazon RDS, customers are given
access to a psuedo-superuser role called rds_superuser, but they
are not given access to superuser. However, rds_superusers will
otherwise have the ability to execute pg_repack commands in RDS.
This change introduces the --no-superuser-check option in the
client code so that users can disable the client-side superuser
checks.
> Introduce --no-superuser-check option.

- bin/pg_repack.c
- doc/pg_repack.rst
- regress/expected/repack.out
- regress/sql/repack.sql
Hi guys,
I'm one of the developers of [pg_pathman](https://github.com/postgrespro/pg_pathman), a new partitioning tool for PostgreSQL.
Recently, one of our clients had trouble running pg_repack on a DB containing some tables partitioned by pg_pathman. In other words, pg_repack would hang _every time_ when trying to lock `pathman_config`, a table that we use to store partitioning configuration. As it turns out, when pg_repack opens a secondary connection and performs any query, our `post_parse_analyze_hook` comes into play and tries to read `pathman_config` (for planning purposes), which is impossible, hence the deadlock :(
This gave me an idea that it would be nice if we could make pg_repack forget about `pathman_config` and other tables that belong to their extensions. There might always …
> new option 'include-extensions' (don't touch tables that belong to extensions)

- bin/pg_repack.c
Total 3 issues were noticed by the coverity scan but other two issues were not problem actually.
> Fix a small memory leak in repack_one_database function.

- bin/pg_repack.c
- regress/expected/repack.out
- regress/expected/repack_1.out
- regress/sql/repack.sql
Commit 5adff6ff0b88d6f162719eff7176069730537c2a separated the
data copy from creating table. This is a cause of bug that
pg_repack doesn't actually sort table during reorganization.
This commit fixes this issue by adding ORDER BY clause to Copy
SQL rather than CREATE TABLE SQL.
Reported by acmzero on issue #138.
> Fix reorganize table without sorting.

- regress/expected/repack.out
- regress/expected/repack_1.out
- regress/expected/repack_2.out
- regress/sql/repack.sql
The regression test could fail on some environments such as where
the encoding is SQL_ASCII.
Fixed issue #130.
> Change to use only the characters that are printable ASCII.

- lib/pg_repack.sql.in
- lib/repack.c
- regress/expected/repack.out
- regress/expected/repack_1.out
- regress/expected/repack_2.out
- regress/expected/repack_3.out
- regress/expected/repack_4.out
- regress/expected/repack_5.out
- regress/expected/repack_6.out
- regress/expected/tablespace_2.out
- regress/expected/tablespace_3.out
- regress/sql/repack.sql
Due to change at PostgreSQL 10.3, 9.6.8, 9.5.12, 9.4.17 and 9.3.22,
relation names passed by PostgreSQL function such as
pg_get_indexdef_string() are schema-qualified, which could be cause
of a parse error.
> Always qualify relation names.

- bin/pgut/pgut.c
Currently pg_repack requires some duplicate password prompt although I expect only one password prompt.
For example if table space is not specified, password prompt required twice. If table space is specified, password prompt required four times.
So this PR removes some duplicate password prompt.
- Before
```
$ pg_repack --no-superuser-check --table=testtbl --dbname=test --host=postgres-test.c5x5yhkaqvsm.us-west-2.rds.amazonaws.com --port=5432 --username=hayshogo --password --elevel=DEBUG --tablespace=testspace
DEBUG: No workers to disconnect.
Password: 
Password: 
DEBUG: No workers to disconnect.
Password: 
Password: 
INFO: repacking table "testtbl"
DEBUG: ---- repack_one_table ----
DEBUG: target_name       : testtbl
DEBUG: target_oid        : 24628
:
:
```
- After
```
$ pg_repack …
```
> Remove duplicate password prompt

- bin/pgut/pgut-fe.c
- bin/pgut/pgut.c
A pull request that solves a side effect by a patch that addresses the vulnerability CVE-2018-1058.
=============
What is the problem?
-------------
When pg_repack is executed in parallel, it does not find the operator class installed in the public schema.
```
Issue items.
https://github.com/reorg/pg_repack/issues/187
https://github.com/reorg/pg_repack/issues/185
```
cause of problem
-------------
The PGConn used when there are two or more walkers sets the search_path to pg_catalog, pg_temp at the setup_workers function.
```
https://github.com/reorg/pg_repack/blob/9bfd94562e77ead67dfcc1713916f862a4a8ee4d/bin/pgut/pgut-fe.c#L46
pgut_command(conn, "SET search_path TO pg_catalog, pg_temp", 0, NULL);
```
Therefore, the PGConn used in parallel processing cannot find the operator class …
> Fix a parallel processing fails for indexes with operators from public schema.

- README.rst
Except for the pg_reorg link, which seems to be dead (for me, anyway).
> Use HTTPS URLs everywhere in README.rst

- .gitignore
- .travis.yml
- META.json
- doc/pg_repack.rst
- lib/repack.c
Hello.
It is me again and my new patch for the upcoming PostgreSQL release v13.
- compatibility macroses heap_open and head_close [was removed](https://git.postgresql.org/gitweb/?p=postgresql.git;a=commitdiff;h=f25968c49697db673f6cd2a07b3f7626779f1827) in postgresql.
This seems to be the only incompatible change so far.
> Support for postgresql 13

- .travis.yml
- META.json
- bin/pg_repack.c
- bin/pgut/pgut.c
- doc/pg_repack.rst
- lib/pg_repack.sql.in
- lib/repack.c
- regress/expected/repack-check.out
- regress/travis_prepare.sh
Hello
I think I am ready to publish a new patchset to support the postgresql 14 release. I found several changes that we need to address:
- SQL function `array_append` was changed. Most noticeable part, already mentioned in #276 . Instead of fixing the `repack.array_accum` custom aggregate function, I want to drop it and use native PostgreSQL string_agg and array_agg functions instead. They are both old enough.
- API of `simple_prompt` function was changed again
- I replaced few SearchSysCacheCopy calls to encouraged macro. This fixes segfault on pg14 for me, but still not sure why exactly.
- postgresql 14 start producing `CONTEXT:  unnamed portal parameter $2 = '...'` in case of `--table relation_not_exists`. Looks weird. I added explicit check for tables existence
- also I temporary …
> Support for postgresql 14

- bin/pgut/pgut-fe.c
- bin/pgut/pgut-fe.h
Postgresql 15 beta1 is here. Luckily, we only have one minor change: postgresql commit 98e93a1fc93e9b54eb477d870ec744e9e1669f34 removed include of pwd.h and breaks build. I decided to replace your own implementation of get_username and use the generic get_user_name_or_exit from the postgresql code. Exists since postgresql 9.4, so no change in supported versions.
> support for postgresql 15

- doc/pg_repack.rst
- lib/repack.c
- regress/Makefile
- regress/expected/get_order_by.out
- regress/sql/get_order_by.sql
When pass an invalid Oid to `get_order_by` function it lead to a segmentation full in function `get_relation_name`.
Fixed if by raising an error when a table is not found.
Fixes #321
> Fix segfault in get_order_by function

- .github/workflows/regression.yml
All github actions that run on Node12 are deprecated so bumped `checkout` github action version to run on Node16.
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
> Bump checkout github action version

- bin/pg_repack.c
- bin/pgut/pgut.h
Try to get the lock in loop with timeouts using `lock_exclusive()`. This allows to not stuck lock queue for readers if pg_repack cannot take the lock fast enough.
We had incidents when cleanup functions, which run `repack.repack_drop()`, couldn't get ACCESS EXCLUSIVE lock in a reasonable time. It was because there was long running write connections, running around 5-10 minutes. `repack.repack_drop()` also stucks lock queue block any new readers until all old writes finish.
> Take ACCESS EXCLUSIVE LOCK carefully

- bin/pg_repack.c
- doc/pg_repack.rst
- doc/pg_repack_jp.rst
- regress/Makefile
- regress/expected/error-on-invalid-idx.out
- regress/expected/error-on-invalid-idx_1.out
- regress/sql/error-on-invalid-idx.sql
Currently, when we find an incorrect index, we only show warning. With --error-on-invalid-index flag, there'll be an error and repack will be stopped. It's done to prevent corruption of indexes. Index may be corrupted if repack is interrupted, then index is updated, and then repack is done completely.
> Flag for stopping repack when invalid index is found

- bin/pg_repack.c
- doc/pg_repack.rst
- doc/pg_repack_jp.rst
The option `-F, --error-on-invalid-index` was added by https://github.com/reorg/pg_repack/pull/336.
Short name for this option is unnecessary and can be removed.
> Remove unnecessary short option name for `--error-on-invalid-index`

- bin/pg_repack.c
- doc/pg_repack.rst
- doc/pg_repack_jp.rst
- regress/expected/repack-check.out
- regress/sql/repack-check.sql
This is rebased patch from https://github.com/reorg/pg_repack/pull/261.
Differences:
- There is no unnecessary short option name `-r`
- Default threshold value is `100`
- New test for `--switch-threshold`
> Rebase: new option "switch-threshold"

- bin/pgut/pgut.c
This PR enhances https://github.com/reorg/pg_repack/pull/350. In addition to increasing of buffer size it removes restrictions on password length for Postgres 14+.
As it was discussed starting from [this comment](https://github.com/reorg/pg_repack/pull/350#issuecomment-1516559391) it is possible to remove the restriction completely by copying `simple_prompt` function from the Postgres 14+ source code into pg_repack code base. But this looks more complicate than removing the restriction only for Postgres 14+, because it will be necessary to support that code in the future.
It is possible to remove the restriction completely in the future if it will be decided that it is better.
> Support larger password lengths v2

- bin/pg_repack.c
> Revert "pg_repack.c"

- bin/pg_repack.c
On a busy database, if statement_timeout=100, then "RESET statement_timeout" can take more than 100ms and fail. So use lock_timeout instead, available since PostgreSQL 9.3.
> fix #200 lock_timeout instead of statement_timeout

- META.json
- bin/pg_repack.c
- lib/pg_repack.sql.in
- lib/repack.c
- regress/Makefile
- regress/expected/tablespace.out
- regress/expected/tablespace_1.out
- regress/expected/tablespace_2.out
- regress/expected/tablespace_3.out
- regress/expected/tablespace_4.out
- regress/expected/trigger.out
- regress/sql/tablespace.sql
- regress/sql/trigger.sql
Making INSERT query in C prevents SQL injections, which are possible if an INSERT query is passed as an argument.
Here is an example with "old" `repack.repack_trigger`:
```
CREATE EXTENSION pg_repack;
CREATE TABLE public.t1 (a int);
CREATE TABLE public.t2 (b varchar);
INSERT INTO public.t2 VALUES (current_user);
CREATE TRIGGER repack_trigger AFTER INSERT ON public.t1
FOR EACH ROW EXECUTE PROCEDURE repack.repack_trigger('INSERT INTO public.t2 VALUES (current_user)');
INSERT INTO public.t1 VALUES (1);
SELECT b FROM public.t2;
b 
----------
bob
postgres 
```
It is possible to move `repack.get_index_columns` to C too. But list of columns is passed as an argument as for now for the sake of simplicity.
Additionally this commit adds funtions:
- repack.create_index_type
- repack.create_log_table …
> Move INSERT query of `repack.repack_trigger` to C

- doc/pg_repack.rst
- doc/pg_repack_jp.rst
Add PostgrerSQL16 into supported versions into `docs/pg_repack.rst` and `docs/pg_repack_jp.rst`.
Tests were added by https://github.com/reorg/pg_repack/pull/364.
We probably could delete oldest PostgreSQL versions which are not listed in https://github.com/reorg/pg_repack/blob/6263dd5e7fcb2890c68b4237591628c4ad08259d/.github/workflows/regression.yml#L10-L16
> Add PostgrerSQL16 into supported versions

- lib/repack.c
Table OID should be unsigned four-byte integer, therefore formatting with %d is wrong. %u should be used as in other places.
It's surprising that we haven't received such error messages before. But such a query is definitely wrong: 
```
INSERT INTO repack.log_-907750756(pk, row) ...
```
I have no idea how to add a test with large OID.
> Fix wrong OID format type in repack_trigger

- META.json
- lib/pg_repack.sql.in
- regress/expected/after-schema.out
- regress/expected/after-schema_1.out
- regress/expected/after-schema_2.out
- regress/expected/error-on-invalid-idx.out
- regress/expected/error-on-invalid-idx_1.out
- regress/expected/repack-check.out
- regress/expected/repack-run.out
- regress/expected/repack-setup.out
- regress/expected/repack-setup_1.out
- regress/sql/after-schema.sql
- regress/sql/repack-check.sql
PostgreSQL 11 introduced covering indexes. pg_repack couldn't use indexes which include additional columns because all columns are listed in `pg_index.indkey`. To overcome this it is necessary to consider `pg_index.indnkeyatts` value.
In `lib/pg_repack.sql.in` I had to define two versions of `repack.primary_keys` since `pg_index.indnkeyatts` was added only in PostgreSQL 11. Otherwise it would be necessary to drop support of PostgreSQL 10 and below.
Issue: https://github.com/reorg/pg_repack/issues/282
> Issue 282: Fix check of NOT NULL by repack.primary_keys

- .github/workflows/regression.yml
- bin/pg_repack.c
- regress/create_tablespaces.sh
- regress/expected/tablespace.out
- regress/expected/tablespace_1.out
- regress/expected/tablespace_2.out
- regress/expected/tablespace_3.out
- regress/expected/tablespace_4.out
- regress/sql/tablespace.sql
It isn't necessary to call `quote_ident()` within `repack_one_database()`. `tablespace_dest` is passed to `repack.create_table()`, which already calls `quote_ident()`.
`quote_ident()` within `repack_one_database()` can return quoted `tablespace_dest`, calling `quote_ident()` second time will make unexpected tablespace name with surrounding quotes.
Tests were added.
Issue: https://github.com/reorg/pg_repack/issues/386
> Issue 386: Do not call quote_ident() within repack_one_database()

- bin/pgut/pgut-fe.c
- bin/pgut/pgut.c
- bin/pgut/pgut.h
A value in a connection string should be quoted if it can contain spaces:
https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING-KEYWORD-VALUE
Alternative approach is to use `PQconnectdbParams()` instead of `PQconnectdb()`. This should be more solid approach to pass password and other connection options, which doesn't require escaping value strings.
Issue: #382
> Replace `PQconnectdb()` by `PQconnectdbParams()`

- .github/workflows/regression.yml
- regress/expected/repack-check.out
- regress/sql/repack-check.sql
Hello
Feature freeze for postgresql 17 has started.
We need no actual code changes. Just a small tweak in the tests to support nullable attsstattarget: https://www.postgresql.org/message-id/flat/4da8d211-d54d-44b9-9847-f2a9f1184c76@eisentraut.org
> Support for postgresql 17

- bin/pg_repack.c
- doc/pg_repack.rst
- regress/expected/repack-check.out
- regress/sql/repack-check.sql
- Add a new apply-count command line parameter to allow tuning of the REDO apply_count variable.
- Check on startup that switch_threshold is not greater or equal to apply_count, which would cause REDO to stop after the first apply_log call (fwiw this bug also exists in 1.5.0, since switch_threshold parameter was added but was not checked against the default APPLY_COUNT of 1000).
- Tuning apply_count might be useful for improving REDO performance on tables with small tuples that receive lots of updates.
- Fixes https://github.com/reorg/pg_repack/issues/393
> Add apply-count parameter

- bin/pg_repack.c
- regress/expected/repack-check.out
- regress/expected/repack-check_1.out
- regress/expected/repack-check_2.out
- regress/expected/repack-check_3.out
- regress/sql/repack-check.sql
When the option `--only-indexes` is used it doesn't make sense to repack indexes of a decoratively partitioned table since they don't store data. Therefore we can just ignore parent tables within the function `repack_all_indexes()`.
Issue: https://github.com/reorg/pg_repack/issues/389
> Issue #389: Do not include a declaratively partitioned table with option `--only-indexes`

- lib/repack.c
This PR is follow up of https://github.com/reorg/pg_repack/pull/157.
- I fixed the typo: https://github.com/reorg/pg_repack/pull/157#issuecomment-1519195513
- I removed `PG_VERSION_NUM >= 90300` check since we don't support such old versions anyway
- I added check `relform1->relkind != RELKIND_INDEX` since `relfrozenxid` and `relminmxid` is non-zero only for tables
I think we still need to check the current state of `swap_relation_files` (https://github.com/postgres/postgres/blob/ae69c4fcf1337af399a788ab8d96af540bd1cd8e/src/backend/commands/cluster.c?plain=1#L1055). It has a few differences with the code of `repack.c`. We don't need to copy all the code, since not all features are supported by pg_repack. For example we don't repack system tables, mapped tables. And maybe we don't need to …
> Fix swap of relfrozenxid, relfrozenxid and relallvisible

- bin/pg_repack.c
- lib/repack.c
Previously, while swapping the target table and its temp table, we used to acquire an AccessExclusiveLock on only the target table but not on its temp table. So the following scenario could happen:
1. Run (auto) vacuum on the temp table.
2. Swap the target table's relfile node and the temp table's relfilenode, and commit.
3. Run (auto) vacuum on the target table.
1 and 3 run concurrently on different tables but these tables use the same relfilenode. In the reported case, since concurrent changes (INSERT/UPDATE/DELETE) can also run concurrently, the second vacuum ended up removing newly added tuples.
To fix the issue, this commit changes the pg_repack command so that it acquires an AcessExclusiveLock also on the temp table before swapping these tables.
Issue: #399
> Fix possible two vacuums concurrently processing the same relfilenode.

- bin/pg_repack.c
In lock_access_share() function, before acquiring an AccessShareLock on the target table, concurrent DDL commands are terminated unconditionally. However, there is a window between this termination and the actual "LOCK TABLE ... IN ACCESS SHARE MODE" operation, allowing other DDL commands to run on the target table. If the LOCK TABLE failed due to a lock conflict, the transaction was rolled back and retried to execute LOCK TABLE, but the LOCK TABLE command could not be executed again as the transaction had already closed.
This commit fixes the issue by using SAVEPOINT and ROLLBACK TO SAVEPOINT so that we can retry to take a lock in the same top transaction.
Issue #383
> Use savepoints when retrying to take AccessShareLock.

- lib/repack.c
commit [0cecc908e9749101b5e93ba58d76a62c9f226f9e](https://github.com/postgres/postgres/commit/0cecc908e9749101b5e93ba58d76a62c9f226f9e) in postgresql changed the signature of the LockHeldByMe function, which caused the pg_repack build to fail.
Actually, the orstronger argument is not important for us, since we need the strictest AccessExclusiveLock lock. But I can simplify the code a little by using a more appropriate new CheckRelationOidLockedByMe function.
> fix LockHeldByMe compilation error against pg17

- lib/pgut/pgut-spi.c
We have a fork postgres that also contains pg_repack and get warning in gcc 12.2.1 that stop build (we have set option "threat warnings as errors"), hope it will be usefull in community version
> Remove compliation warning of unitialized value

- META.json
- bin/pgut/pgut.c
- doc/pg_repack.rst
- doc/pg_repack_jp.rst
- lib/repack.c
- regress/expected/nosuper.out
- regress/expected/nosuper_1.out
- regress/sql/nosuper.sql
The option `--no-superuser-check` allows to by-pass the check if the user is a superuser. That was done for users which run pg_repack on Amazon, where users cannot run it as a superuser.
The problem is that the option `--no-superuser-check` works only on the CLI level, skipping the check only by the `pg_repack` client. But there are also checks done by the extension functions exported to SQL.
The PR removes the check that the user is a superuser from functions `repack_trigger()` and `repack_apply()`. That check is redundant since queries executed by that functions can be executed by a user manually. Moreover `repack_trigger()` is a `SECURITY DEFINER` function, which means that it is executed with superuser privileges (`pg_repack` extension can be created only by superuser).
The PR changes …
> Allow to run pg_repack by non-superuser

- bin/pg_repack.c
- doc/pg_repack.rst
- doc/pg_repack_jp.rst
- regress/Makefile
- regress/expected/no-error-on-invalid-idx.out
- regress/expected/no-error-on-invalid-idx_1.out
- regress/expected/repack-run.out
- regress/sql/no-error-on-invalid-idx.sql
Skipping repacking the invalid indexes could lead to corrupting the invalid indexes. In some rare cases, this might cause inserts to tables to fail as changes to a table continuously be applied to invalid indexes on it and updates to corrupted invalid indexes potentially might fail by the checks done during insertion. Therefore, by default do not repack a table with invalid indexes. Repack only user explicitly specifies --no-error-on-invalid-index.
> Issue #422: Make --error-on-invalid-index the default behavior

- doc/pg_repack.rst
Looks like we are ready to make new release and there are no urgent issues which stops it.
Just add release notes. The version was already bumped within META.json before.
> Release of pg_repack 1.5.2

- bin/pg_repack.c
When using `--only-indexes` `pg_repack` uses different approach to repack indexes, which is running CREATE INDEX CONCURRENTLY command to create a temporary index and swapping the target index and the temporary index afterwards.
That approach didn't use any cleanup callbacks and therefore in case of an error temporary indexes wouldn't be cleaned up.
The commit adds the callback `repack_cleanup_index`.
Issue: #437
> Issue #437: Cleanup temporary indexes on error (with --only-indexes)

- .github/workflows/regression.yml
[Feature freeze day](https://www.postgresql.org/message-id/Z_U0fUvVkXOZmRVV%40momjian.us)! It looks like nothing needs to be changed this year to support the new release. Add pg18 to the tests.
> postgresql 18

- .gitignore
- bin/pg_repack.c
- doc/pg_repack.rst
- doc/pg_repack_jp.rst
Currently conn2 acquires `ACCESS SHARE` lock which allows to run concurrent DDL statements, like `CREATE INDEX CONCURRENTLY`.
Fix it by acquiring `SHARE UPDATE EXCLUSIVE` lock. This will also lock concurrent `VACUUM`, `ANALYZE` queries, locking them looks safer option anyway.
Thoughts?
Issue #420
> Issue #420: Acquire SHARE UPDATE EXCLUSIVE by conn2

- .github/workflows/regression.yml
- bin/pg_repack.c
- regress/expected/nosuper.out
- regress/expected/nosuper_1.out
`lock_access_share()` and `lock_exclusive()` doesn't call RELEASE SAVEPOINT on every retry which pollutes the cache and degrades the performance. This commit calls RELEASE SAVEPOINT when created savepoint is not necessary anymore. Additionally it moves SAVEPOINT outside of the retry loop since it isn't necessary to create new savepoint on every retry at all.
`lock_exclusive()` also moves start of transaction outside of the retry loop and creates a savepoint regardless of the value `start_xact`.
Now Github workflow also installs `libnuma-dev` for PostgreSQL 18 since it has new option `--with-libnuma`:
https://www.postgresql.org/docs/18/release-18.html
> Add configure option --with-libnuma to enable NUMA awareness (Jakub Wartak, Bertrand Drouvot)
Issue #457
> Issue #457: Move SAVEPOINT outside the retry loop and call RELEASE SAVEPOINT
